### PR TITLE
update README.md, api.md as well as add Table of Contents and a screenshot

### PR DESCRIPTION
**Pull request by gianpaj**
Great project!
While I was following the instructions I noticed few things could be improved :) 

Feel free to let me know if there's something else I missed or I shouldn't have done

### CODE REVIEW

**Review by andrealeo83 — APPROVED** [review]
image

**Review by andrealeo83 — APPROVED** [review]
image

**Review by andrealeo83 — APPROVED** [review]
readme

**Comment by andrealeo83** [comment]
thanks you @gianpaj

**Comment by gianpaj** [comment]
no problem @andrealeo83 🙂

**Pull request merged**
